### ISSUE TITLE
Compilation Errror with openssl1.1 and g++  9.5.0, ubuntu 22.04

### ISSUE THREAD

**Issue by cheenng** [bmwcarit/MoCOCrW#135]
Dear all,

I'm facing a compilation error:

```
/home/ycheng/MoCOCrW/src/openssl_lib.cpp:788:32: error: invalid conversion from ‘const ec_key_st*’ to ‘EC_KEY*’ {aka ‘ec_key_st*’} [-fpermissive]
  788 |     return EVP_PKEY_get0_EC_KEY(pkey);
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                |
      |                                const ec_key_st*
```

Can you please help me on this? Thanks a lot!

**Comment by neverpanic** [comment]
Ubuntu 22.04 uses OpenSSL 3. Try the `openssl3.0` branch.

**Comment by cheenng** [comment]
@neverpanic  thanks for the reply. However, the error persists:
```
/home/ycheng/MoCOCrW/src/openssl_lib.cpp:762:32: error: invalid conversion from ‘const ec_key_st*’ to ‘EC_KEY*’ {aka ‘ec_key_st*’} [-fpermissive]
  762 |     return EVP_PKEY_get0_EC_KEY(pkey);
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                |
      |                                const ec_key_st*
```

**Comment by garw** [comment]
Hi,

unfortunately, OpenSSL 3 support isn't really ready yet. The error looks to me like some of the const-correctness fixes that were made in OpenSSL 3. Maybe this was also introduced after we did the initial OpenSSL 3 evaluation. 
Maybe I can have a quick look throughout the next days but I cannot guarantee anything. OpenSSL 3 support is only on our agenda for later this year.

**Comment by cheenng** [comment]
Hi @garw  thanks a lot for the reply. I will close the issue.
