### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by ghost** [bmwcarit/MoCOCrW#2]
Few questions about versioning:
- Any plan to reflect the version of MoCOCrw also in git?
- How does the version of the library is supposed to change? Is MoCOCrW using https://semver.org/ ?

**Comment by blenk92** [comment]
Hi, sorry for the late reply. We've finally added versioning and releases. 

For details see https://github.com/bmwcarit/MoCOCrW/blob/openssl1.1/RELEASING.md
